/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package canteen.management.system;
import javax.swing.JOptionPane;


/**
 *
 * @author Shivani
 */
public class Home extends javax.swing.JFrame {

    public String email;
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    public Home(String userEmail) {
        initComponents();
        email=userEmail;
        if(!email.equals("admin123@gmail.com"))
        {
            btnManageCat.setVisible(false);
             btnNewPro.setVisible(false);
              btnView.setVisible(false);
               btnVerify.setVisible(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogout = new javax.swing.JButton();
        btnPlaceOrder = new javax.swing.JButton();
        btnViewBill = new javax.swing.JButton();
        btnChangePass = new javax.swing.JButton();
        btnChangeSecQues = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnManageCat = new javax.swing.JButton();
        btnNewPro = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnVerify = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogout.setBackground(new java.awt.Color(204, 204, 204));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout_1.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        btnPlaceOrder.setBackground(new java.awt.Color(204, 204, 204));
        btnPlaceOrder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPlaceOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/placeorder_2.png"))); // NOI18N
        btnPlaceOrder.setText("Place Order");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlaceOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        btnViewBill.setBackground(new java.awt.Color(204, 204, 204));
        btnViewBill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnViewBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/viewbill_1.png"))); // NOI18N
        btnViewBill.setText("View Bill & Order Placed Details");
        btnViewBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBillActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        btnChangePass.setBackground(new java.awt.Color(204, 204, 204));
        btnChangePass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChangePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/changepass.png"))); // NOI18N
        btnChangePass.setText("Change Password");
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });
        getContentPane().add(btnChangePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, -1, -1));

        btnChangeSecQues.setBackground(new java.awt.Color(204, 204, 204));
        btnChangeSecQues.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChangeSecQues.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/changesecurity_1.png"))); // NOI18N
        btnChangeSecQues.setText("Change Security Question");
        btnChangeSecQues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeSecQuesActionPerformed(evt);
            }
        });
        getContentPane().add(btnChangeSecQues, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 30, -1, -1));

        btnExit.setBackground(new java.awt.Color(204, 204, 204));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        btnExit.setText("Exit ");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 30, -1, -1));

        btnManageCat.setBackground(new java.awt.Color(204, 204, 204));
        btnManageCat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnManageCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/category_1.png"))); // NOI18N
        btnManageCat.setText("Manage Category");
        btnManageCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCatActionPerformed(evt);
            }
        });
        getContentPane().add(btnManageCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, -1, -1));

        btnNewPro.setBackground(new java.awt.Color(204, 204, 204));
        btnNewPro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNewPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/neworder_1.png"))); // NOI18N
        btnNewPro.setText("New Product");
        btnNewPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewProActionPerformed(evt);
            }
        });
        getContentPane().add(btnNewPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 710, -1, -1));

        btnView.setBackground(new java.awt.Color(204, 204, 204));
        btnView.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editdelete_1.png"))); // NOI18N
        btnView.setText("View Edit & Delete Product");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        getContentPane().add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 710, -1, -1));

        btnVerify.setBackground(new java.awt.Color(204, 204, 204));
        btnVerify.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/verify_1.png"))); // NOI18N
        btnVerify.setText("Verify User");
        btnVerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerify, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 710, -1, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/main_1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBillActionPerformed
        // TODO add your handling code here:
        new ViewBillOrderPlaceDetails().setVisible(true);
    }//GEN-LAST:event_btnViewBillActionPerformed

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed
        // TODO add your handling code here:
        new ChangePassword(email).setVisible(true);
    }//GEN-LAST:event_btnChangePassActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
         int a = JOptionPane.showConfirmDialog(null, "Do you really want to Logout", "Select", JOptionPane.YES_NO_OPTION);
         if(a==0){
             setVisible(false);
             new Login().setVisible(true);
         }
        
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
         int a = JOptionPane.showConfirmDialog(null, "Do you really want to Close Application", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnManageCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCatActionPerformed
        // TODO add your handling code here:
        new ManageCategory().setVisible(true);
    }//GEN-LAST:event_btnManageCatActionPerformed

    private void btnNewProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewProActionPerformed
        // TODO add your handling code here:
     new   AddNewProduct().setVisible(true);
    }//GEN-LAST:event_btnNewProActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
   
            new ViewEditDeleteProduct().setVisible(true);
    
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyActionPerformed
        // TODO add your handling code here:
        new VerifyUsers().setVisible(true);
    }//GEN-LAST:event_btnVerifyActionPerformed

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new PlaceOrder(email).setVisible(true);
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void btnChangeSecQuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeSecQuesActionPerformed
        // TODO add your handling code here:
         new ChangeSecurityQuestion(email).setVisible(true);
    }//GEN-LAST:event_btnChangeSecQuesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePass;
    private javax.swing.JButton btnChangeSecQues;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageCat;
    private javax.swing.JButton btnNewPro;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton btnVerify;
    private javax.swing.JButton btnView;
    private javax.swing.JButton btnViewBill;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
